### ISSUE TITLE
uploading Topic files

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Courses#113]
all files uploaded to topic as content (Audio/Video/PDF etc) must be stored inside `course/{id}` folder in storage/

This refers to 

- [ ] all upload methods
- [ ] course/topic seeder

**Comment by qunabu** [comment]
@pa-cholek any suggestions how this should be done properlly

**Comment by pa-cholek** [comment]
I'm not really sure what do you mean by "properly", is there a wrong way to do this? XD

I'm pretty sure that all topic resources are currently uploaded to `/topic/:id/resources` and all topic content files are uploaded to `/topic/:id`? It shouldn't be too hard to change this to use topic parent course id in path... and all filenames are randomly generated because we use `UploadedFile->store()` method.

To upload in seeder, we can just use `Storage::put('courses/:id/filename.ext', $content);` where `$content = file_get_contents('../path/to/file.ext')` and just store correct file path in Topic model? 
In TopicFactory we copy files in `updatePath` factory state modyfing method, and `->state()` passess model attributes to closure, so we can just access `$attributes['course_id']` for getting correct path.
